import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    // Nav
    home: "Home",
    govtSchemes: "Government Schemes",
    aboutUs: "About Us",
    services: "Services",
    contact: "Contact",
    signIn: "Sign In",
    register: "Register",
    signOut: "Sign Out",
    dashboard: "Dashboard",
    language: "Language",
    // General
    name: "Name",
    email: "Email Address",
    phone: "Phone Number",
    address: "Address",
    message: "Message",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save Changes",
    edit: "Edit Profile",
    loading: "Loading...",
    // About Page
    ourStory: "Our Story",
    empoweringAgri: "Empowering Indian Agriculture",
    storyDesc: "AgroLink is the next-generation supply-chain layer connecting crop farmers and commercial buyers directly, based in Tuljapur, Maharashtra.",
    ourMission: "Our Mission",
    missionDesc: "To eliminate non-value-adding middle layers, ensure fair crop profit shares reach producers immediately, and decrease post-harvest crop wastage through temperature-controlled logistics and modern cold storage.",
    ourVision: "Our Vision",
    visionDesc: "To turn Indian agricultural commerce into a fully secure, digital-first experience that improves food supply speeds and leverages AI price insights.",
    teamBehind: "The Team Behind AgroLink",
    teamDesc: "Engineered with care and production stability standards for smart agriculture.",
    hqAddress: "AgroLink Tuljapur Office",
    productOps: "Product Operations",
    qualityAssurance: "Quality & Assurance",
    // Contact Page
    getInTouch: "Get in touch",
    contactTeam: "Contact Our Team",
    contactDesc: "Have questions about AgroLink? Reach out and we will respond immediately.",
    contactInfo: "Contact Information",
    contactInfoDesc: "Contact our customer care lines or visit our offices for help setting up cold storages or farm profiles.",
    callUs: "Call Us",
    emailSupport: "Email Support",
    officeAddress: "Office Address",
    sendInquiry: "Send an Inquiry",
    sending: "Sending Message...",
    messageSentSuccess: "Message sent successfully!",
    // Services Page
    ourServices: "Our Services",
    platformServices: "Platform Services",
    servicesDesc: "Direct supply systems designed to streamline agricultural trading across Maharashtra.",
    directTrade: "Direct Trade Marketplace",
    directTradeDesc: "Connect crop producers and commercial buyers directly to ensure fair commodity pricing.",
    escrowHold: "Secure Escrow Logistics",
    escrowHoldDesc: "Lock funds safely during transit, transferring only upon verified receipt validation.",
    smartLogistics: "Smart Cold Storage Booking",
    smartLogisticsDesc: "Reserve warehouse spaces and track climate conditions to prevent harvest deterioration.",
    // Login / Register
    loginTitle: "Sign In to AgroLink",
    loginSubtitle: "Direct Farm-to-Buyer Access Platform",
    password: "Password",
    selectRole: "Select Portal Access Role",
    farmer: "Farmer Portal",
    buyer: "Wholesaler / Buyer",
    coldStorageManager: "Cold Storage Facility Manager",
    systemAdmin: "System Administrator",
    noAccount: "Don't have an account?",
    hasAccount: "Already registered?",
    registerTitle: "Create Account",
    registerSubtitle: "Join Maharashtra's direct agricultural supply network",
    step1: "Step 1: Core Credentials",
    step2: "Step 2: Role Details",
    uploadAvatar: "Upload Custom Profile Avatar",
    selectPreset: "Or select a preset organic avatar",
    farmSize: "Farm Size (Acres)",
    mandiLicense: "Mandi License Number (APMC)",
    storageCapacity: "Storage Facility Capacity (MT)",
    // Profile Page
    profileTitle: "Profile Management",
    profileSubtitle: "Update your personal details, contact coordinates, and profile photo.",
    saveChanges: "Save Profile Changes",
    savingDetails: "Saving Profile Details...",
    phoneLabel: "Contact Phone",
    roleDetails: "Role-Specific Parameters",
    // Weather
    weatherForecast: "Live Weather Forecast",
    humidity: "Humidity",
    windSpeed: "Wind Speed",
    locationPermission: "Requires location permission to query local coordinates.",
    requestingLocation: "Requesting coordinates...",
    // Mandi
    mandiRates: "Live APMC Mandi Rates",
    mandiSub: "Real-time market price index movements across Maharashtra APMCs",
    crop: "Crop",
    price: "Average Price",
    trend: "24h Fluctuation",
    // Buyer Dashboard
    produceMarketplace: "Produce Marketplace",
    purchasedOrders: "Purchased Orders",
    favoritesListings: "Favorites Listings",
    shoppingCart: "Shopping Cart",
    checkoutDetails: "Checkout Details",
    deliveryAddress: "Delivery / Shipping Address",
    addressPrepopulated: "Pre-populated from your profile. Changes will update your active default address.",
    produceCost: "Produce Cost",
    logisticsFee: "Logistics Fee",
    grandTotalEscrow: "Grand Total (Escrow)",
    checkoutSecureEscrow: "Checkout & Secure Escrow",
    securingEscrow: "Securing Escrow Funds...",
    rate: "Rate",
    qty: "Qty (qtl)",
    total: "Total",
    items: "items",
    buyNow: "Buy Now",
    addCart: "Add Cart",
    searchCrops: "Search crops (e.g. Tomato, Wheat)...",
    filterHarvestLocation: "Filter by harvest location...",
    available: "Available",
    pricePerQtl: "Price per qtl",
    cropItem: "Crop Item",
    seller: "Seller",
    purchaseQty: "Purchase Quantity (Quintals)",
    escrowCheckout: "Escrow Checkout",
    securingTransactionsEscrow: "Securing transactions through AgroLink Escrow reserves.",
    heroTitle: "Direct Farm-to-Market Platform",
    heroSubtitle: "Empowering Maharashtra's Farmers with Real-time Trades, Secure Escrows, and Cold Storage Logistics.",
    getStarted: "Get Started",
    learnMore: "Learn More",
    // Payment Modal
    paymentGateway: "AgroLink Secure Escrow Gateway",
    paymentGatewaySubtitle: "Secure Escrow Payment Gateway System",
    paymentAmount: "Payment Amount",
    paymentMethod: "Payment Method",
    cardPayment: "Credit / Debit Card",
    upiPayment: "UPI / QR Code",
    netBanking: "Net Banking",
    cardNumber: "Card Number",
    expiryDate: "Expiry Date",
    cvv: "CVV",
    cardholderName: "Cardholder Name",
    upiIdPlaceholder: "UPI ID (e.g., username@upi)",
    paySecurely: "Pay Securely",
    scanQr: "Scan QR Code to Pay",
    selectBank: "Select Your Bank",
    authenticating: "Contacting Gateway Bank...",
    otpTitle: "Bank Authentication",
    otpSubtitle: "Simulating Secure OTP Validation",
    otpLabel: "Enter 6-Digit OTP sent to your registered phone",
    otpPlaceholder: "Enter 6-digit OTP",
    verifyComplete: "Verify & Complete Escrow",
    verifying: "Verifying Code...",
    txSuccess: "Transaction Successful!",
    txSuccessSubtitle: "Your payment has been successfully placed into AgroLink Escrow.",
    txId: "Transaction Reference ID",
    viewOrders: "View Purchased Orders",
    // Farmer Portal
    farmerPortal: "Farmer Portal Dashboard",
    listCrop: "List Crop Produce",
    myListings: "My Active Listings",
    coldStorageLeases: "Cold Storage Leases",
    salesHistory: "My Crop Sales History",
    cropVariety: "Crop Variety",
    locationHarvest: "Harvest Location",
    priceQuintal: "Price per Quintal (₹)",
    qtyQuintals: "Quantity Available (Quintals)",
    descriptionCrop: "Description / Notes",
    photoCrop: "Produce Harvest Photo",
    submitListing: "Publish Crop Listing",
    creatingListing: "Publishing crop to marketplace...",
    // Cold Storage Portal
    coldStoragePortal: "Cold Storage Warehouse Dashboard",
    iotTelemetry: "IoT Climate Telemetry Monitor",
    bookingsRequests: "Lease Space Booking Requests",
    occupancyRate: "Warehouse Occupancy Rate",
    tempSensor: "Facility Temperature (IoT Sensor)",
    humiditySensor: "Facility Humidity (IoT Sensor)",
    // Admin Portal
    adminPortal: "System Administration Desk",
    platformAnalytics: "System-Wide Performance Analytics",
    systemSettings: "Escrow & Platform Configurations",
    complaintsDesk: "Disputes & Complaints Board",
    catalogsControl: "Active Product Marketplace Catalogs",
    // Step 3 Registration
    step3Farmer: "Step 3: Location & Final Details",
    step3Buyer: "Step 3: Contact & Address",
    step3Storage: "Step 3: Location & Capacity",
    state: "State",
    district: "District / City",
    upiId: "UPI ID",
    contactPerson: "Contact Person",
    officialPhone: "Official Phone",
    streetAddress: "Street Address / Facility Details",
    streetAddressStorage: "Street Address / Area Location",
    storageRate: "Rate per Ton/Day (₹)",
    registerProfile: "Register Profile",
    back: "Back",
    // Admin Mandi Control
    mandiControl: "Mandi Rates Control",
    usersControl: "Users Control",
    productsControl: "Products Control",
    complaints: "Complaints",
    settings: "Settings",
    addMandiRate: "Add Crop Rate",
    editMandiRate: "Edit Crop Rate",
    cropName: "Crop Name",
    variety: "Variety",
    marketName: "Market Name",
    pricePerQuintal: "Price per Quintal",
    priceChangeYesterday: "24h Fluctuation",
    action: "Action",
    confirmDelete: "Are you sure you want to remove this Mandi price record?",
    mandiDashboard: "Mandi Desk Control",
    // Farmer Dashboard Additions
    farmerCommandCenter: "Farmer Command Center",
    incomingOrders: "Incoming Orders",
    earningsRegistry: "Earnings Registry",
    reserveColdStorage: "Reserve Cold Storage",
    totalEarnings: "Total Earnings",
    pendingOrders: "Pending Orders",
    activeBookings: "Active Bookings",
    facilityName: "Facility Name",
    facilityDesc: "Facility Description",
    storageCapacityLabel: "Total Capacity (Tons)",
    storageRateLabel: "Rate per Ton/Day (₹)",
    // Cold Storage Dashboard Additions
    coldStorageCommand: "Cold Storage Command",
    bookingSpaceQueue: "Booking Space Queue",
    activeWarehousingRecords: "Active Warehousing Records",
    totalSpace: "Total Space",
    iotAirTemp: "IoT Air Temp",
    pendingLeases: "Pending Leases",
    activeLeases: "Active Leases",
    occupancyGauge: "Occupancy Gauge",
    occupancyDesc: "Current spatial volume utilization ratios.",
    // Profile Page Additions
    changeAvatar: "Change Avatar",
    personalDetails: "Personal Details"
  },
  mr: {
    // Nav
    home: "मुख्यपृष्ठ",
    govtSchemes: "सरकारी योजना",
    aboutUs: "आमच्याबद्दल",
    services: "सेवा",
    contact: "संपर्क",
    signIn: "लॉगिन करा",
    register: "नोंदणी करा",
    signOut: "बाहेर पडा",
    dashboard: "डॅशबोर्ड",
    language: "भाषा",
    // General
    name: "नाव",
    email: "ईमेल पत्ता",
    phone: "फोन नंबर",
    address: "पत्ता",
    message: "संदेश",
    submit: "प्रविष्ट करा",
    cancel: "रद्द करा",
    save: "बदल जतन करा",
    edit: "प्रोफाइल संपादित करा",
    loading: "लोड होत आहे...",
    // About Page
    ourStory: "आमची कहाणी",
    empoweringAgri: "भारतीय शेतीचे सक्षमीकरण",
    storyDesc: "अॅग्रोलिंक ही थेट पीक शेतकरी आणि व्यापारी खरेदीदारांना जोडणारी पुढील पिढीची पुरवठा साखळी आहे, जी तुळजापूर, महाराष्ट्र येथे स्थित आहे.",
    ourMission: "आमचे ध्येय",
    missionDesc: "मध्यस्थांचे उच्चाटन करणे, शेतकऱ्यांना पिकांचा योग्य नफा त्वरित मिळवून देणे आणि तापमान-नियंत्रित लॉजिस्टिक्स आणि आधुनिक कोल्ड स्टोरेजद्वारे काढणीनंतरचे नुकसान कमी करणे.",
    ourVision: "आमची दृष्टी",
    visionDesc: "भारतीय कृषी व्यापाराला संपूर्ण सुरक्षित, डिजिटल-प्रथम अनुभवामध्ये रूपांतरित करणे, ज्यामुळे अन्न पुरवठा वेगवान होईल आणि एआय किमतीचे विश्लेषण मिळेल.",
    teamBehind: "अॅग्रोलिंक मागील संघ",
    teamDesc: "स्मार्ट शेतीसाठी काळजी आणि उत्पादन स्थिरता मानकांसह तयार केले गेले आहे.",
    hqAddress: "अॅग्रोलिंक तुळजापूर कार्यालय",
    productOps: "उत्पादन ऑपरेशन्स",
    qualityAssurance: "गुणवत्ता आणि हमी",
    // Contact Page
    getInTouch: "संपर्क साधा",
    contactTeam: "आमच्या टीमशी संपर्क साधा",
    contactDesc: "अॅग्रोलिंकबद्दल प्रश्न आहेत? संपर्क साधा आणि आम्ही त्वरित प्रतिसाद देऊ.",
    contactInfo: "संपर्क माहिती",
    contactInfoDesc: "कोल्ड स्टोरेज किंवा शेत प्रोफाइल सेटअपमध्ये मदतीसाठी आमच्या ग्राहक सेवा लाईन्सशी संपर्क साधा किंवा आमच्या कार्यालयांना भेट द्या.",
    callUs: "आम्हाला कॉल करा",
    emailSupport: "ईमेल समर्थन",
    officeAddress: "कार्यालयाचा पत्ता",
    sendInquiry: "चौकशी संदेश पाठवा",
    sending: "संदेश पाठवला जात आहे...",
    messageSentSuccess: "संदेश यशस्वीरित्या पाठवला गेला!",
    // Services Page
    ourServices: "आमच्या सेवा",
    platformServices: "प्लॅटफॉर्म सेवा",
    servicesDesc: "महाराष्ट्रातील शेती व्यापाराला सुलभ करण्यासाठी थेट पुरवठा प्रणाली.",
    directTrade: "थेट व्यापार बाजारपेठ",
    directTradeDesc: "पिकांचे योग्य मूल्य मिळवण्यासाठी पीक उत्पादक आणि व्यापारी खरेदीदारांना थेट जोडा.",
    escrowHold: "सुरक्षित एस्क्रो लॉजिस्टिक्स",
    escrowHoldDesc: "वाहतुकीदरम्यान निधी सुरक्षितपणे लॉक करा, केवळ सत्यापित पावती मिळाल्यावरच हस्तांतरित करा.",
    smartLogistics: "स्मार्ट कोल्ड स्टोरेज बुकिंग",
    smartLogisticsDesc: "पिकांची हानी रोखण्यासाठी वेअरहाउस जागा आरक्षित करा आणि हवामान परिस्थितीचा मागोवा घ्या.",
    // Login / Register
    loginTitle: "अॅग्रोलिंकमध्ये साइन इन करा",
    loginSubtitle: "थेट शेतकरी-ते-खरेदीदार प्रवेश प्लॅटफॉर्म",
    password: "पासवर्ड",
    selectRole: "पोर्टल प्रवेश भूमिका निवडा",
    farmer: "शेतकरी पोर्टल",
    buyer: "घाऊक विक्रेता / खरेदीदार",
    coldStorageManager: "कोल्ड स्टोरेज सुविधा व्यवस्थापक",
    systemAdmin: "सिस्टम प्रशासक",
    noAccount: "खाते नाही का?",
    hasAccount: "आधीच नोंदणीकृत आहात का?",
    registerTitle: "खाते तयार करा",
    registerSubtitle: "महाराष्ट्राच्या थेट कृषी पुरवठा नेटवर्कमध्ये सामील व्हा",
    step1: "पायरी १: मुख्य क्रेडेंशियल",
    step2: "पायरी २: भूमिकेचा तपशील",
    uploadAvatar: "सानुकूल प्रोफाइल फोटो अपलोड करा",
    selectPreset: "किंवा प्रीसेट ऑरगॅनिक फोटो निवडा",
    farmSize: "शेत आकार (एकर)",
    mandiLicense: "मंडी परवाना क्रमांक (APMC)",
    storageCapacity: "साठवण सुविधा क्षमता (MT)",
    // Profile Page
    profileTitle: "प्रोफाइल व्यवस्थापन",
    profileSubtitle: "तुमचे वैयक्तिक तपशील, संपर्क समन्वय आणि प्रोफाइल फोटो अपडेट करा.",
    saveChanges: "प्रोफाइल बदल जतन करा",
    savingDetails: "प्रोफाइल तपशील जतन करत आहे...",
    phoneLabel: "संपर्क फोन",
    roleDetails: "भूमिका-विशिष्ट मापदंड",
    // Weather
    weatherForecast: "थेट हवामान अंदाज",
    humidity: "आर्द्रता",
    windSpeed: "वाऱ्याचा वेग",
    locationPermission: "स्थानिक हवामानासाठी स्थान परवानगी आवश्यक आहे.",
    requestingLocation: "स्थान मिळवत आहे...",
    // Mandi
    mandiRates: "थेट एपीएमसी मंडी दर",
    mandiSub: "महाराष्ट्र एपीएमसी मधील रिअल-टाइम बाजार भावांची हालचाल",
    crop: "पीक",
    price: "सरासरी किंमत",
    trend: "२४ तासांतील चढ-उतार",
    // Buyer Dashboard
    produceMarketplace: "उत्पादन बाजारपेठ",
    purchasedOrders: "खरेदी केलेल्या ऑर्डर्स",
    favoritesListings: "आवडत्या याद्या",
    shoppingCart: "खरेदी कार्ट",
    checkoutDetails: "चेकआउट तपशील",
    deliveryAddress: "वितरण / पाठवण्याचा पत्ता",
    addressPrepopulated: "तुमच्या प्रोफाईलवरून आपोआप भरले आहे. बदल केल्यास तुमचा मूळ पत्ता अपडेट होईल.",
    produceCost: "उत्पादन खर्च",
    logisticsFee: "वाहतूक शुल्क",
    grandTotalEscrow: "एकूण शुल्क (एस्क्रो)",
    checkoutSecureEscrow: "चेकआउट आणि सुरक्षित एस्क्रो",
    securingEscrow: "एस्क्रो निधी सुरक्षित करत आहे...",
    rate: "दर",
    qty: "प्रमाण (क्विंटल)",
    total: "एकूण",
    items: "वस्तू",
    buyNow: "आता खरेदी करा",
    addCart: "कार्टमध्ये जोडा",
    searchCrops: "पिके शोधा (उदा. टोमॅटो, गहू)...",
    filterHarvestLocation: "पीक स्थानानुसार फिल्टर करा...",
    available: "उपलब्ध",
    pricePerQtl: "प्रति क्विंटल दर",
    cropItem: "पीक उत्पादन",
    seller: "विक्रेता",
    purchaseQty: "खरेदी प्रमाण (क्विंटल)",
    escrowCheckout: "एस्क्रो चेकआउट",
    securingTransactionsEscrow: "अॅग्रोलिंक एस्क्रोद्वारे व्यवहार सुरक्षित केले जात आहेत.",
    heroTitle: "थेट शेतकरी-ते-बाजार प्लॅटफॉर्म",
    heroSubtitle: "महाराष्ट्रातील शेतकऱ्यांना रिअल-टाइम व्यापार, सुरक्षित एस्क्रो आणि कोल्ड स्टोरेज लॉजिस्टिक्ससह सक्षम करणे.",
    getStarted: "सुरू करूया",
    learnMore: "अधिक जाणून घ्या",
    // Payment Modal
    paymentGateway: "अॅग्रोलिंक सुरक्षित एस्क्रो गेटवे",
    paymentGatewaySubtitle: "सुरक्षित एस्क्रो पेमेंट गेटवे सिस्टीम",
    paymentAmount: "पेमेंट रक्कम",
    paymentMethod: "पेमेंट पद्धत",
    cardPayment: "क्रेडिट / डेबिट कार्ड",
    upiPayment: "UPI / QR कोड",
    netBanking: "नेट बँकिंग",
    cardNumber: "कार्ड क्रमांक",
    expiryDate: "कालबाह्यता तारीख",
    cvv: "सीव्हीव्ही",
    cardholderName: "कार्डधारकाचे नाव",
    upiIdPlaceholder: "UPI आयडी (उदा. username@upi)",
    paySecurely: "सुरक्षित पेमेंट करा",
    scanQr: "पेमेंट करण्यासाठी QR कोड स्कॅन करा",
    selectBank: "तुमची बँक निवडा",
    authenticating: "गेटवे बँकेशी संपर्क साधत आहे...",
    otpTitle: "बँक प्रमाणीकरण",
    otpSubtitle: "सुरक्षित OTP पडताळणी सिम्युलेशन",
    otpLabel: "तुमच्या नोंदणीकृत फोनवर पाठवलेला ६-अंकी OTP प्रविष्ट करा",
    otpPlaceholder: "६-अंकी OTP प्रविष्ट करा",
    verifyComplete: "OTP सत्यापित करा आणि एस्क्रो पूर्ण करा",
    verifying: "कोड सत्यापित करत आहे...",
    txSuccess: "व्यवहार यशस्वी झाला!",
    txSuccessSubtitle: "तुमचे पेमेंट अॅग्रोलिंक एस्क्रोमध्ये यशस्वीरित्या जमा झाले आहे.",
    txId: "व्यवहार संदर्भ आयडी",
    viewOrders: "खरेदी केलेल्या ऑर्डर्स पहा",
    // Farmer Portal
    farmerPortal: "शेतकरी पोर्टल डॅशबोर्ड",
    listCrop: "पीक उत्पन्नाची नोंदणी करा",
    myListings: "माझ्या सक्रिय पीक याद्या",
    coldStorageLeases: "कोल्ड स्टोरेज लीज जागा",
    salesHistory: "माझा पीक विक्री इतिहास",
    cropVariety: "पिकाची जात",
    locationHarvest: "काढणीचे ठिकाण",
    priceQuintal: "किंमत प्रति क्विंटल (₹)",
    qtyQuintals: "उपलब्ध प्रमाण (क्विंटल)",
    descriptionCrop: "वर्णन / टीप",
    photoCrop: "पीक काढणीचा फोटो",
    submitListing: "पीक यादी प्रकाशित करा",
    creatingListing: "बाजारपेठेत पीक प्रकाशित करत आहे...",
    // Cold Storage Portal
    coldStoragePortal: "कोल्ड स्टोरेज वेअरहाउस डॅशबोर्ड",
    iotTelemetry: "आयओटी हवामान टेलीमेट्री मॉनिटर",
    bookingsRequests: "लीज जागा बुकिंग विनंत्या",
    occupancyRate: "वेअरहाउस वापर दर",
    tempSensor: "सुविधा तापमान (आयओटी सेन्सर)",
    humiditySensor: "सुविधा आर्द्रता (आयओटी सेन्सर)",
    // Admin Portal
    adminPortal: "सिस्टम प्रशासन डेस्क",
    platformAnalytics: "सिस्टम-व्यापी कार्यप्रदर्शन विश्लेषण",
    systemSettings: "एस्क्रो आणि प्लॅटफॉर्म कॉन्फिगरेशन",
    complaintsDesk: "तक्रार आणि वाद निवारण बोर्ड",
    catalogsControl: "सक्रिय उत्पादन बाजार कॅटलॉग",
    // Step 3 Registration
    step3Farmer: "पायरी ३: स्थान आणि अंतिम तपशील",
    step3Buyer: "पायरी ३: संपर्क आणि पत्ता",
    step3Storage: "पायरी ३: स्थान आणि क्षमता",
    state: "राज्य",
    district: "जिल्हा / शहर",
    upiId: "UPI आयडी",
    contactPerson: "संपर्क व्यक्ती",
    officialPhone: "अधिकृत फोन",
    streetAddress: "पत्ता / सुविधा तपशील",
    streetAddressStorage: "पत्ता / क्षेत्र स्थान",
    storageRate: "दर प्रति टन/दिवस (₹)",
    registerProfile: "प्रोफाइल नोंदणी करा",
    back: "मागे",
    // Admin Mandi Control
    mandiControl: "मंडी दर नियंत्रण",
    usersControl: "वापरकर्ता नियंत्रण",
    productsControl: "उत्पादन नियंत्रण",
    complaints: "तक्रारी",
    settings: "सेटिंग्ज",
    addMandiRate: "मंडी दर जोडा",
    editMandiRate: "मंडी दर संपादित करा",
    cropName: "पिकाचे नाव",
    variety: "पिकाची जात",
    marketName: "बाजारपेठ",
    pricePerQuintal: "प्रति क्विंटल दर",
    priceChangeYesterday: "२४ तासांतील बदल",
    action: "कृती",
    confirmDelete: "तुम्हाला खात्री आहे की तुम्ही हा रेकॉर्ड हटवू इच्छिता?",
    mandiDashboard: "मंडी नियंत्रण डेस्क",
    // Farmer Dashboard Additions
    farmerCommandCenter: "शेतकरी नियंत्रण केंद्र",
    incomingOrders: "आलेल्या ऑर्डर्स",
    earningsRegistry: "उत्पन्न नोंदवही",
    reserveColdStorage: "कोल्ड स्टोरेज आरक्षित करा",
    totalEarnings: "एकूण उत्पन्न",
    pendingOrders: "प्रलंबित ऑर्डर्स",
    activeBookings: "सक्रिय बुकिंग्ज",
    facilityName: "सुविधेचे नाव",
    facilityDesc: "सुविधेचे वर्णन",
    storageCapacityLabel: "एकूण क्षमता (टन)",
    storageRateLabel: "दर प्रति टन/दिवस (₹)",
    // Cold Storage Dashboard Additions
    coldStorageCommand: "कोल्ड स्टोरेज नियंत्रण",
    bookingSpaceQueue: "बुकिंग जागा रांग",
    activeWarehousingRecords: "सक्रिय साठवणूक रेकॉर्ड",
    totalSpace: "एकूण जागा",
    iotAirTemp: "IoT हवेचे तापमान",
    pendingLeases: "प्रलंबित लीज",
    activeLeases: "सक्रिय लीज",
    occupancyGauge: "वापर पातळी",
    occupancyDesc: "सध्याचे जागा वापर प्रमाण.",
    // Profile Page Additions
    changeAvatar: "फोटो बदला",
    personalDetails: "वैयक्तिक तपशील"
  },
  hi: {
    // Nav
    home: "मुख्यपृष्ठ",
    govtSchemes: "सरकारी योजनाएं",
    aboutUs: "हमारे बारे में",
    services: "सेवाएं",
    contact: "संपर्क",
    signIn: "लॉगिन करें",
    register: "पंजीकरण",
    signOut: "साइन आउट",
    dashboard: "डैशबोर्ड",
    language: "भाषा",
    // General
    name: "नाम",
    email: "ईमेल पता",
    phone: "फोन नंबर",
    address: "पता",
    message: "संदेश",
    submit: "जमा करें",
    cancel: "रद्द करें",
    save: "बदलाव सहेजें",
    edit: "प्रोफ़ाइल संपादित करें",
    loading: "लोड हो रहा है...",
    // About Page
    ourStory: "हमारी कहानी",
    empoweringAgri: "भारतीय कृषि का सक्षमीकरण",
    storyDesc: "एग्रोलिंक सीधा फसल उत्पादक किसानों और व्यावसायिक खरीदारों को जोड़ने वाली अगली पीढ़ी की आपूर्ति श्रृंखला है, जो तुलजापुर, महाराष्ट्र में स्थित है.",
    ourMission: "हमारा उद्देश्य",
    missionDesc: "बिचौलियों को खत्म करना, उत्पादकों को फसल का उचित लाभ तुरंत सुनिश्चित करना और तापमान-नियंत्रित लॉजिस्टिक्स और आधुनिक कोल्ड स्टोरेज के माध्यम से फसल की बर्बादी को कम करना.",
    ourVision: "हमारा दृष्टिकोण",
    visionDesc: "भारतीय कृषि व्यापार को पूरी तरह से सुरक्षित, डिजिटल-प्रथम अनुभव में बदलना, जिससे खाद्य आपूर्ति की गति तेज हो और एआई मूल्य विश्लेषण का लाभ मिले.",
    teamBehind: "एग्रोलिंक के पीछे की टीम",
    teamDesc: "स्मार्ट कृषि के लिए देखभाल और उत्पादन स्थिरता मानकों के साथ तैयार किया गया है.",
    hqAddress: "एग्रोलिंक तुलजापुर कार्यालय",
    productOps: "उत्पाद संचालन",
    qualityAssurance: "गुणवत्ता और आश्वासन",
    // Contact Page
    getInTouch: "संपर्क करें",
    contactTeam: "हमारी टीम से संपर्क करें",
    contactDesc: "एग्रोलिंक के बारे में प्रश्न हैं? संपर्क करें और हम तुरंत प्रतिक्रिया देंगे.",
    contactInfo: "संपर्क विवरण",
    contactInfoDesc: "कोल्ड स्टोरेज या फार्म प्रोफाइल सेटअप में मदद के लिए हमारी ग्राहक सेवा लाइनों से संपर्क करें या हमारे कार्यालयों में आएं.",
    callUs: "हमें कॉल करें",
    emailSupport: "ईमेल समर्थन",
    officeAddress: "कार्यालय का पता",
    sendInquiry: "पूछताछ संदेश भेजें",
    sending: "संदेश भेजा जा रहा है...",
    messageSentSuccess: "संदेश सफलतापूर्वक भेजा गया!",
    // Services Page
    ourServices: "हमारी सेवाएं",
    platformServices: "मंच सेवाएं",
    servicesDesc: "महाराष्ट्र में कृषि व्यापार को सरल बनाने के लिए तैयार की गई प्रत्यक्ष आपूर्ति प्रणालियां.",
    directTrade: "प्रत्यक्ष व्यापार बाजार",
    directTradeDesc: "फसल उत्पादकों और व्यावसायिक खरीदारों को सीधे जोड़कर उचित मूल्य निर्धारण सुनिश्चित करें.",
    escrowHold: "सुरक्षित एस्क्रो लॉजिस्टिक्स",
    escrowHoldDesc: "परिवहन के दौरान सुरक्षित रूप से धन को लॉक करें, केवल सत्यापित रसीद मिलने पर ही जारी करें.",
    smartLogistics: "स्मार्ट कोल्ड स्टोरेज बुकिंग",
    smartLogisticsDesc: "फसल के नुकसान को रोकने के लिए गोदामों में जगह आरक्षित करें और मौसम की स्थिति की निगरानी करें.",
    // Login / Register
    loginTitle: "एग्रोलिंक में लॉग इन करें",
    loginSubtitle: "सीधा किसान-से-खरीदार पहुंच मंच",
    password: "पासवर्ड",
    selectRole: "पोर्टल भूमिका का चयन करें",
    farmer: "किसान पोर्टल",
    buyer: "थोक व्यापारी / खरीदार",
    coldStorageManager: "कोल्ड स्टोरेज सुविधा प्रबंधक",
    systemAdmin: "सिस्टम प्रशासक",
    noAccount: "खाता नहीं है?",
    hasAccount: "पहले से पंजीकृत हैं?",
    registerTitle: "खाता बनाएं",
    registerSubtitle: "महाराष्ट्र के प्रत्यक्ष कृषि आपूर्ति नेटवर्क में शामिल हों",
    step1: "चरण १: मुख्य क्रेडेंशियल",
    step2: "चरण २: भूमिका विवरण",
    uploadAvatar: "कस्टम प्रोफ़ाइल फ़ोटो अपलोड करें",
    selectPreset: "या प्रीसेट जैविक फ़ोटो चुनें",
    farmSize: "फार्म का आकार (एकड़)",
    mandiLicense: "मंडी लाइसेंस संख्या (APMC)",
    storageCapacity: "भंडारण सुविधा क्षमता (MT)",
    // Profile Page
    profileTitle: "प्रोफ़ाइल प्रबंधन",
    profileSubtitle: "अपनी व्यक्तिगत जानकारी, संपर्क विवरण और प्रोफ़ाइल फ़ोटो अपडेट करें.",
    saveChanges: "बदलाव सहेजें",
    savingDetails: "प्रोफ़ाइल विवरण सहेजा जा रहा है...",
    phoneLabel: "संपर्क फोन",
    roleDetails: "भूमिका-विशिष्ट पैरामीटर",
    // Weather
    weatherForecast: "सीधा मौसम पूर्वानुमान",
    humidity: "आर्द्रता",
    windSpeed: "हवा की गति",
    locationPermission: "स्थानीय मौसम के लिए स्थान अनुमति आवश्यक है.",
    requestingLocation: "स्थान प्राप्त किया जा रहा है...",
    // Mandi
    mandiRates: "सीधा एपीएमसी मंडी दरें",
    mandiSub: "महाराष्ट्र एपीएमसी में वास्तविक समय के बाजार भावों का सूचकांक",
    crop: "फसल",
    price: "औसत मूल्य",
    trend: "२४ घंटे का उतार-चढ़ाव",
    // Buyer Dashboard
    produceMarketplace: "उत्पाद बाजार",
    purchasedOrders: "खरीदे गए ऑर्डर्स",
    favoritesListings: "पसंदीदा लिस्टिंग",
    shoppingCart: "शॉपिंग कार्ट",
    checkoutDetails: "चेकआउट विवरण",
    deliveryAddress: "वितरण / वितरण पता",
    addressPrepopulated: "आपकी प्रोफ़ाइल से स्वतः भरा हुआ। बदलाव आपके डिफ़ॉल्ट पते को अपडेट करेंगे।",
    produceCost: "उत्पाद लागत",
    logisticsFee: "लॉजिस्टिक्स शुल्क",
    grandTotalEscrow: "कुल योग (एस्क्रो)",
    checkoutSecureEscrow: "चेकआउट और सुरक्षित एस्क्रो",
    securingEscrow: "एस्क्रो फंड सुरक्षित किया जा रहा है...",
    rate: "दर",
    qty: "मात्रा (क्विंटल)",
    total: "कुल",
    items: "सामग्री",
    buyNow: "अभी खरीदें",
    addCart: "कार्ट में जोड़ें",
    searchCrops: "फसलें खोजें (जैसे टमाटर, गेहूं)...",
    filterHarvestLocation: "कटाई स्थान द्वारा फ़िल्टर करें...",
    available: "उपलब्ध",
    pricePerQtl: "मूल्य प्रति क्विंटल",
    cropItem: "फसल सामग्री",
    seller: "विक्रेता",
    purchaseQty: "खरीद मात्रा (क्विंटल)",
    escrowCheckout: "एस्क्रो चेकआउट",
    securingTransactionsEscrow: "एग्रोलिंक एस्क्रो के माध्यम से लेनदेन सुरक्षित किए जा रहे हैं।",
    heroTitle: "सीधा किसान-से-बाजार मंच",
    heroSubtitle: "महाराष्ट्र के किसानों को रीयल-टाइम व्यापार, सुरक्षित एस्क्रो और कोल्ड स्टोरेज लॉजिस्टिक्स के साथ सशक्त बनाना।",
    getStarted: "शुरू करें",
    learnMore: "अधिक जानें",
    // Payment Modal
    paymentGateway: "एग्रोलिंक सुरक्षित एस्क्रो गेटवे",
    paymentGatewaySubtitle: "सुरक्षित एस्क्रो भुगतान गेटवे प्रणाली",
    paymentAmount: "भुगतान राशि",
    paymentMethod: "भुगतान विधि",
    cardPayment: "क्रेडिट / डेबिट कार्ड",
    upiPayment: "UPI / QR कोड",
    netBanking: "नेट बैंकिंग",
    cardNumber: "कार्ड संख्या",
    expiryDate: "समाप्ति तिथि",
    cvv: "सीव्हीव्ही",
    cardholderName: "कार्डधारक का नाम",
    upiIdPlaceholder: "UPI आईडी (जैसे, username@upi)",
    paySecurely: "सुरक्षित भुगतान करें",
    scanQr: "भुगतान के लिए QR कोड स्कैन करें",
    selectBank: "अपना बैंक चुनें",
    authenticating: "गेटवे बैंक से संपर्क कर रहा है...",
    otpTitle: "बैंक प्रमाणीकरण",
    otpSubtitle: "सुरक्षित OTP सत्यापन सिमुलेशन",
    otpLabel: "अपने पंजीकृत फोन पर भेजा गया 6-अंकीय OTP दर्ज करें",
    otpPlaceholder: "6-अंकीय OTP दर्ज करें",
    verifyComplete: "OTP सत्यापित करें और एस्क्रो पूरा करें",
    verifying: "कोड सत्यापित किया जा रहा है...",
    txSuccess: "लेनदेन सफल रहा!",
    txSuccessSubtitle: "आपका भुगतान एग्रोलिंक एस्क्रो में सफलतापूर्वक जमा कर दिया गया है।",
    txId: "लेनदेन संदर्भ आईडी",
    viewOrders: "खरीदे गए ऑर्डर्स देखें",
    // Farmer Portal
    farmerPortal: "किसान पोर्टल डैशबोर्ड",
    listCrop: "फसल पंजीकरण करें",
    myListings: "मेरी सक्रिय सूची",
    coldStorageLeases: "कोल्ड स्टोरेज लीज स्थान",
    salesHistory: "मेरा फसल बिक्री इतिहास",
    cropVariety: "फसल की किस्म",
    locationHarvest: "कटाई का स्थान",
    priceQuintal: "मूल्य प्रति क्विंटल (₹)",
    qtyQuintals: "उपलब्ध मात्रा (क्विंटल)",
    descriptionCrop: "विवरण / टिप्पणी",
    photoCrop: "फसल कटाई का फोटो",
    submitListing: "फसल सूची प्रकाशित करें",
    creatingListing: "बाजार में फसल प्रकाशित की जा रही है...",
    // Cold Storage Portal
    coldStoragePortal: "कोल्ड स्टोरेज गोदाम डैशबोर्ड",
    iotTelemetry: "आईओटी मौसम टेलीमेट्री मॉनिटर",
    bookingsRequests: "लीज स्थान बुकिंग अनुरोध",
    occupancyRate: "गोदाम उपयोग दर",
    tempSensor: "सुविधा तापमान (आईओटी सेंसर)",
    humiditySensor: "सुविधा आर्द्रता (आईओटी सेंसर)",
    // Admin Portal
    adminPortal: "सिस्टम प्रशासन डेस्क",
    platformAnalytics: "सिस्टम-व्यापी प्रदर्शन विश्लेषण",
    systemSettings: "एस्क्रो और प्लेटफॉर्म कॉन्फ़िगरेशन",
    complaintsDesk: "शिकायत और विवाद निवारण बोर्ड",
    catalogsControl: "सक्रिय उत्पाद बाजार कैटलॉग",
    // Step 3 Registration
    step3Farmer: "चरण ३: स्थान और अंतिम विवरण",
    step3Buyer: "चरण ३: संपर्क और पता",
    step3Storage: "चरण ३: स्थान और क्षमता",
    state: "राज्य",
    district: "जिला / शहर",
    upiId: "UPI आईडी",
    contactPerson: "संपर्क व्यक्ति",
    officialPhone: "आधिकारिक फोन",
    streetAddress: "पता / सुविधा विवरण",
    streetAddressStorage: "पता / क्षेत्र स्थान",
    storageRate: "दर प्रति टन/दिन (₹)",
    registerProfile: "प्रोफ़ाइल पंजीकृत करें",
    back: "पीछे",
    // Admin Mandi Control
    mandiControl: "मंडी दर नियंत्रण",
    usersControl: "उपयोगकर्ता नियंत्रण",
    productsControl: "उत्पाद नियंत्रण",
    complaints: "शिकायतें",
    settings: "सेटिंग्स",
    addMandiRate: "मंडी दर जोड़ें",
    editMandiRate: "मंडी दर संपादित करें",
    cropName: "फसल का नाम",
    variety: "विविधता / किस्म",
    marketName: "मंडी / बाजार",
    pricePerQuintal: "मूल्य प्रति क्विंटल",
    priceChangeYesterday: "२४ घंटे का बदलाव",
    action: "कार्रवाई",
    confirmDelete: "क्या आप वाकई इस रिकॉर्ड को हटाना चाहते हैं?",
    mandiDashboard: "मंडी नियंत्रण डेस्क",
    // Farmer Dashboard Additions
    farmerCommandCenter: "किसान नियंत्रण केंद्र",
    incomingOrders: "आने वाले ऑर्डर",
    earningsRegistry: "कमाई रजिस्ट्री",
    reserveColdStorage: "कोल्ड स्टोरेज आरक्षित करें",
    totalEarnings: "कुल कमाई",
    pendingOrders: "लंबित ऑर्डर",
    activeBookings: "सक्रिय बुकिंग",
    facilityName: "सुविधा का नाम",
    facilityDesc: "सुविधा का विवरण",
    storageCapacityLabel: "कुल क्षमता (टन)",
    storageRateLabel: "दर प्रति टन/दिन (₹)",
    // Cold Storage Dashboard Additions
    coldStorageCommand: "कोल्ड स्टोरेज नियंत्रण",
    bookingSpaceQueue: "बुकिंग स्थान कतार",
    activeWarehousingRecords: "सक्रिय भंडारण रिकॉर्ड",
    totalSpace: "कुल स्थान",
    iotAirTemp: "IoT हवा का तापमान",
    pendingLeases: "लंबित लीज",
    activeLeases: "सक्रिय लीज",
    occupancyGauge: "उपयोग स्तर",
    occupancyDesc: "वर्तमान स्थान उपयोग अनुपात।",
    // Profile Page Additions
    changeAvatar: "फोटो बदलें",
    personalDetails: "व्यक्तिगत विवरण"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('agrolink_lang');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('agrolink_lang', language);

    // Sync with hidden Google Translate element
    const syncGoogleTranslate = (langCode) => {
      const selectEl = document.querySelector('.goog-te-combo');
      if (selectEl) {
        selectEl.value = langCode;
        selectEl.dispatchEvent(new Event('change'));
      } else {
        let attempts = 0;
        const interval = setInterval(() => {
          const selectRetry = document.querySelector('.goog-te-combo');
          if (selectRetry) {
            selectRetry.value = langCode;
            selectRetry.dispatchEvent(new Event('change'));
            clearInterval(interval);
          }
          attempts++;
          if (attempts > 30) {
            clearInterval(interval);
          }
        }, 200);
      }
    };
    
    syncGoogleTranslate(language);
  }, [language]);

  const t = (key) => {
    const langDict = translations[language] || translations['en'];
    return langDict[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
